repos:
    - repo: https://github.com/ScottChiuNYC/daily_challenge
      rev: v0.1.0
      hooks:
      - id: draw-2025-heatmap
        name: draw 2025 yearly heatmap
        entry: python -c "from daily_challenge import main; main()"
        language: python
        description: "Generate the 2025 yearly heatmap and stage the generated image."
        additional_dependencies: ['matplotlib', 'numpy']